//! Generates the x86_64 syscall table, `$OUT_DIR/syscalls_x86_64.rs`, from
//! the kernel's own `syscall_64.tbl` (vendored in `src/seccomp/`; see
//! `src/seccomp/syscalls.rs` for where it comes from and why).
//!
//! The table has one row per syscall and ABI:
//!
//! ```text
//! <number>  <abi>   <name>        <entry point>
//! 0         common  read          sys_read
//! 13        64      rt_sigaction  sys_rt_sigaction
//! 512       x32     rt_sigaction  compat_sys_rt_sigaction
//! ```
//!
//! Only `common` and `64` rows are native x86_64 syscalls. The `x32` rows
//! (512–547) are the x32 ABI's variants of calls whose argument layout
//! differs; an x32 process issues them with `__X32_SYSCALL_BIT` (bit 30)
//! set, so "rt_sigaction = 512" would be wrong for us. They are dropped.

use std::fmt::Write as _;
use std::path::PathBuf;

const TABLE: &str = "src/seccomp/syscall_64.tbl";

fn main() {
    println!("cargo:rerun-if-changed={TABLE}");
    let text = std::fs::read_to_string(TABLE).unwrap_or_else(|e| panic!("read {TABLE}: {e}"));

    let mut by_number: Vec<(u32, String)> = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut fields = line.split_whitespace();
        let (Some(nr), Some(abi), Some(name)) = (fields.next(), fields.next(), fields.next()) else {
            panic!("{TABLE}:{}: expected `<number> <abi> <name> ...`, got {line:?}", i + 1);
        };
        let nr: u32 = nr.parse().unwrap_or_else(|_| panic!("{TABLE}:{}: bad syscall number {nr:?}", i + 1));
        match abi {
            "common" | "64" => by_number.push((nr, name.to_owned())),
            "x32" => {}
            other => panic!("{TABLE}:{}: unknown abi {other:?}", i + 1),
        }
    }

    by_number.sort();
    for w in by_number.windows(2) {
        assert!(w[0].0 != w[1].0, "{TABLE}: number {} appears twice", w[0].0);
    }
    let mut by_name: Vec<(&str, u32)> = by_number.iter().map(|(nr, name)| (name.as_str(), *nr)).collect();
    by_name.sort();
    for w in by_name.windows(2) {
        assert!(w[0].0 != w[1].0, "{TABLE}: name {} appears twice", w[0].0);
    }
    let highest = by_number.last().expect("the syscall table is empty").0;

    let mut out = String::from("// @generated by build.rs from src/seccomp/syscall_64.tbl. Do not edit.\n\n");
    out.push_str("/// `(number, name)` of every native x86_64 syscall, sorted by number.\n");
    out.push_str("static BY_NUMBER: &[(u32, &str)] = &[\n");
    for (nr, name) in &by_number {
        writeln!(out, "    ({nr}, {name:?}),").unwrap();
    }
    out.push_str("];\n\n/// The same table as `(name, number)`, sorted by name.\n");
    out.push_str("static BY_NAME: &[(&str, u32)] = &[\n");
    for (name, nr) in &by_name {
        writeln!(out, "    ({name:?}, {nr}),").unwrap();
    }
    out.push_str("];\n\n/// The highest syscall number in the table.\n");
    writeln!(out, "pub const HIGHEST: u32 = {highest};").unwrap();

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR")).join("syscalls_x86_64.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
