// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `POST /v1/build`.
 */
export type BuildQuery = { 
/**
 * [`BuildOptions`], as JSON.
 */
options: string, };
