// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStream } from "./LogStream";
import type { PullEvent } from "./PullEvent";

/**
 * One line of the NDJSON `build` response, in order: `context`; then for
 * each stage built, `stage` and its steps; each step `step`, then `cached`
 * or the work (`pull` events for a base image, `container` and `output`
 * for a `RUN`), then `step_done`; last `done`. A failure ends the stream
 * with `error`. `warning`s may come anywhere.
 */
export type BuildEvent = { "type": "context", files: number, bytes: number, } | { "type": "stage", index: number, name: string | null, base: string, } | { "type": "step", step: number, total: number, instruction: string, } | { "type": "pull", event: PullEvent, } | { "type": "cached", step: number, } | { "type": "container", step: number, id: string, } | { "type": "output", step: number, stream: LogStream, text: string, } | { "type": "step_done", step: number, layer: string | null, } | { "type": "warning", message: string, } | { "type": "done", id: string, names: Array<string>, } | { "type": "error", message: string, };
