// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkMode } from "./NetworkMode";
import type { PullPolicy } from "./PullPolicy";

/**
 * What a build is asked to do: the JSON in [`BuildQuery::options`].
 */
export type BuildOptions = { 
/**
 * Names for the image (`-t`): `app`, `registry.example/app:1.0`.
 * Without one, the image is kept unnamed (`rustlet images` lists it as
 * `<none>`) until it is removed by its id.
 */
tags: Array<string>, 
/**
 * The Containerfile's path inside the context; default `Containerfile`,
 * else `Dockerfile`.
 */
dockerfile: string | null, 
/**
 * `--build-arg NAME=VALUE`: values for the file's `ARG`s.
 */
build_args: { [key in string]: string }, 
/**
 * `--target`: build up to this stage (its name, or its index from 0);
 * default the last stage.
 */
target: string | null, 
/**
 * `--no-cache`: run every step again, whatever the cache has.
 */
no_cache: boolean, 
/**
 * When to pull base images: `missing` (default), or `always` (ask the
 * registry what each tag points at now, `--pull`).
 */
pull: PullPolicy, 
/**
 * The network `RUN` steps get: `bridge` (default), `host`, `none`, or a
 * network's name. Not `container:<x>`.
 */
network: NetworkMode, 
/**
 * `--label`: labels for the image, over the Containerfile's `LABEL`s.
 */
labels: { [key in string]: string }, };
