// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The init's capability sets, by name (`CAP_CHOWN`, …), from
 * `/proc/<pid>/status`.
 */
export type Capabilities = { 
/**
 * What the kernel checks now.
 */
effective: Array<string>, 
/**
 * The ceiling of `effective`.
 */
permitted: Array<string>, 
/**
 * What may survive an `execve` (with file or ambient capabilities).
 */
inheritable: Array<string>, 
/**
 * The ceiling of anything the process or its children can ever gain.
 */
bounding: Array<string>, 
/**
 * What survives an `execve` of an ordinary binary.
 */
ambient: Array<string>, 
/**
 * Every capability this kernel knows, in number order, so that the
 * missing ones can be shown too.
 */
known: Array<string>, };
