// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The cgroup's limits beside its usage. `None` for a limit means `max`
 * (none).
 */
export type CgroupUsage = { 
/**
 * Below `/sys/fs/cgroup`.
 */
path: string, memory_current: number, memory_max: number | null, swap_current: number | null, swap_max: number | null, pids_current: number, pids_max: number | null, 
/**
 * `cpu.max`: at most `cpu_quota` microseconds of CPU time per
 * `cpu_period` microseconds (`--cpus 1.5` is 150000 per 100000).
 */
cpu_quota: number | null, cpu_period: number, 
/**
 * `cpu.weight` (1–10000, 100 by default): its share when CPUs are
 * contended.
 */
cpu_weight: number | null, 
/**
 * `cpu.stat` `usage_usec`.
 */
cpu_usage_usec: number, 
/**
 * `memory.events` `oom_kill`.
 */
oom_kills: number, };
