// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `201` from `POST /v1/commit`.
 */
export type CommitResponse = { 
/**
 * The new image's id (manifest digest).
 */
id: string, 
/**
 * Its name, if it was given one.
 */
name: string | null, 
/**
 * The digest of the layer holding the container's changes.
 */
layer: string, };
