// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/commit`: a container's changes as a new image.
 */
export type CommitRequest = { 
/**
 * The container: id, unique id prefix, or name.
 */
container: string, 
/**
 * The new image's name; without one it is kept unnamed.
 */
reference: string | null, 
/**
 * `-m`: the comment of the image's new history entry.
 */
comment: string | null, 
/**
 * `-a`: the image's author.
 */
author: string | null, 
/**
 * Freeze a running container while its changes are read (default
 * true): otherwise a file it writes meanwhile may be caught half-way.
 */
pause: boolean, 
/**
 * `-c`: Containerfile instructions applied to the new image's config:
 * `CMD`, `ENTRYPOINT`, `ENV`, `EXPOSE`, `LABEL`, `ONBUILD`, `USER`,
 * `VOLUME`, `WORKDIR`, `STOPSIGNAL`, `HEALTHCHECK`.
 */
changes: Array<string>, };
