// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerStatus } from "./ContainerStatus";
import type { Health } from "./Health";

/**
 * The part of a container that changes as it runs.
 */
export type ContainerState = { status: ContainerStatus, 
/**
 * Host PID of the container's init, while it is live.
 */
pid: number | null, 
/**
 * The last exit status, shell-style (128 + signal for a signal).
 */
exit_code: number | null, 
/**
 * The kernel's OOM killer killed a process of the container during
 * its last run.
 */
oom_killed: boolean, 
/**
 * Why the last start failed or the last run ended abnormally.
 */
error: string | null, 
/**
 * RFC 3339, UTC.
 */
started_at: string | null, finished_at: string | null, 
/**
 * Restarts by the restart policy since the last `start`/`restart`.
 */
restart_count: number, 
/**
 * While it runs with a healthcheck: what the checks say. Kept after
 * the run, as the last checks said it.
 */
health: Health | null, };
