// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerState } from "./ContainerState";
import type { PublishedPort } from "./PublishedPort";

/**
 * One line of `rustlet ps`: `GET /v1/containers`.
 */
export type ContainerSummary = { id: string, name: string, 
/**
 * As given at create.
 */
image: string, 
/**
 * The image's manifest digest (`sha256:…`).
 */
image_id: string, 
/**
 * What runs: entrypoint + command, resolved against the image.
 */
command: Array<string>, 
/**
 * RFC 3339, UTC.
 */
created: string, state: ContainerState, labels: { [key in string]: string }, 
/**
 * While it runs: its published ports.
 */
ports: Array<PublishedPort>, };
