// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * A text message.
 */
export type Control = { "type": "resize", rows: number, cols: number, } | { "type": "stdin_eof" } | { "type": "hangup" } | { "type": "exit", code: number, oom_killed: boolean, } | { "type": "error", message: string, kind: ErrorKind, };
