// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A container's lifecycle state.
 *
 * ```text
 *  created ──start──► running ⇄ paused
 *     ▲                  │ exits (or is stopped/killed)
 *     │                  ▼
 *     │   start      exited ──(restart policy)──► restarting ──► running
 *     └───────────────── │
 *                        ▼ rm
 *                     removing ──► (gone)
 * ```
 */
export type ContainerStatus = "created" | "running" | "paused" | "restarting" | "exited" | "removing" | "dead";
