// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthConfig } from "./HealthConfig";
import type { MountSpec } from "./MountSpec";
import type { NetworkMode } from "./NetworkMode";
import type { PortMapping } from "./PortMapping";
import type { RestartPolicy } from "./RestartPolicy";
import type { UsernsMode } from "./UsernsMode";

/**
 * `POST /v1/containers`: everything `rustlet run`/`create` can say about a
 * container. Fields left out take the image's value (command, environment,
 * user, working directory) or Rustlets' default.
 */
export type ContainerConfig = { 
/**
 * The image, as typed (`alpine`, `nginx:1.27`, `ghcr.io/o/n@sha256:…`).
 */
image: string, 
/**
 * A unique name ([`crate::valid_container_name`]); one is generated
 * if absent.
 */
name: string | null, 
/**
 * Replaces the image's `Cmd` (`IMAGE ARGS…`).
 */
cmd: Array<string>, 
/**
 * Suppresses the image's `Cmd`, including when `cmd` is empty.
 */
clear_cmd: boolean, 
/**
 * Replaces the image's `Entrypoint`; `Some([])` clears it.
 */
entrypoint: Array<string> | null, 
/**
 * `KEY=VALUE`, over the image's `Env`.
 */
env: Array<string>, 
/**
 * Names removed from the image's environment before applying `env`.
 */
unset_env: Array<string>, 
/**
 * `user[:group]`, names or ids from the image's `/etc/passwd` and
 * `/etc/group`.
 */
user: string | null, workdir: string | null, 
/**
 * Default: the short id.
 */
hostname: string | null, 
/**
 * `-t`: a PTY for the container.
 */
tty: boolean, 
/**
 * `-i`: keep the container's stdin open for attach clients.
 */
open_stdin: boolean, 
/**
 * Close the container's stdin once the first attached client's input
 * ends (`run -i`, as Docker's `StdinOnce`).
 */
stdin_once: boolean, labels: { [key in string]: string }, 
/**
 * `--read-only`: the root filesystem is mounted read-only.
 */
read_only: boolean, userns: UsernsMode, 
/**
 * `--memory`, bytes. Swap on top is not allowed (the memory+swap limit
 * is the same value).
 */
memory: number | null, 
/**
 * `--cpus`: CPU time, in CPUs (`1.5`).
 */
cpus: number | null, 
/**
 * `--pids-limit`; `0` or negative means unlimited.
 */
pids_limit: number | null, restart: RestartPolicy, 
/**
 * `--rm`: remove the container once it has exited (not with a restart
 * policy other than `no`).
 */
auto_remove: boolean, 
/**
 * Signal for `stop` (`SIGTERM`, `TERM` or `15`): the image's
 * `StopSignal`, else `SIGTERM`.
 */
stop_signal: string | null, 
/**
 * Seconds `stop` waits before killing; default 10.
 */
stop_timeout: number | null, 
/**
 * `--health-*`, `--no-healthcheck`: over the image's `HEALTHCHECK`.
 */
healthcheck: HealthConfig | null, 
/**
 * Capability names (`NET_ADMIN`, `CAP_NET_ADMIN`, or `ALL`) to add to
 * and drop from the default set.
 */
cap_add: Array<string>, cap_drop: Array<string>, 
/**
 * `--privileged`: all capabilities, all host devices, no seccomp, no
 * masked paths. Not isolation from host root.
 */
privileged: boolean, 
/**
 * `--security-opt`: `seccomp=unconfined`, `no-new-privileges[=true|false]`.
 */
security_opt: Array<string>, 
/**
 * `--device HOST[:CONTAINER[:rwm]]`: a host device node, with access.
 */
devices: Array<string>, 
/**
 * `--network`: the default network unless given.
 */
network: NetworkMode, 
/**
 * `--network-alias`: more names the embedded DNS server answers for
 * it, on its (first, user-defined) network.
 */
network_aliases: Array<string>, 
/**
 * `--ip`: its IPv4 address on its first network (a user-defined one);
 * default: the next free.
 */
ip: string | null, 
/**
 * `--ip6`: its IPv6 address there (a network with IPv6).
 */
ip6: string | null, 
/**
 * `--network` given again: more networks to connect it to, in order
 * after the first, with no aliases or addresses of their own (`network
 * connect` gives those). Only with a bridge network as the first.
 */
extra_networks: Array<string>, 
/**
 * `-p`: container ports to publish on the host.
 */
ports: Array<PortMapping>, 
/**
 * `-P`: publish every port the image exposes, each on a free host
 * port.
 */
publish_all: boolean, 
/**
 * `--dns`: name servers for the container's `resolv.conf` (or for the
 * embedded DNS server to forward to), instead of the host's.
 */
dns: Array<string>, 
/**
 * `--dns-search`, `--dns-option`: the rest of `resolv.conf`.
 */
dns_search: Array<string>, dns_options: Array<string>, 
/**
 * `--add-host NAME:IP` lines for its `/etc/hosts` (the IP may be
 * `host-gateway`, [`crate::network::HOST_GATEWAY`]).
 */
extra_hosts: Array<string>, 
/**
 * `-v`, `--mount`, `--tmpfs`.
 */
mounts: Array<MountSpec>, };
