// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerConfig } from "./ContainerConfig";
import type { ContainerState } from "./ContainerState";
import type { MountPoint } from "./MountPoint";
import type { NetworkSettings } from "./NetworkSettings";

/**
 * `GET /v1/containers/{id}`.
 */
export type ContainerInspect = { id: string, name: string, created: string, image: string, image_id: string, command: Array<string>, 
/**
 * What it was created with.
 */
config: ContainerConfig, state: ContainerState, hostname: string, 
/**
 * The merged root filesystem on the host, while it is mounted (the
 * container is live).
 */
rootfs: string | null, 
/**
 * The container directory: rootfs, upper (its writable layer), logs.
 */
dir: string, log_path: string, 
/**
 * Its cgroup, as a path below `/sys/fs/cgroup`.
 */
cgroup: string, 
/**
 * `uid_map` of its user namespace (`0 1000000 65536`), if it has one.
 */
uid_map: string | null, network: NetworkSettings, 
/**
 * Its volumes, bind mounts and tmpfs mounts.
 */
mounts: Array<MountPoint>, };
