// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `201` from `POST /v1/containers`.
 */
export type CreateResponse = { id: string, name: string, warnings: Array<string>, };
