// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who the init process is.
 */
export type Credentials = { 
/**
 * Its effective user and group and its supplementary groups now, as
 * the container sees them: the host's ids mapped back through
 * `uid_map`/`gid_map` (an id the maps don't cover is 65534). Usually
 * the user `config.json` started it as, unless it has changed its ids
 * since (an entrypoint that drops to another user with `su-exec`, say).
 */
uid: number, gid: number, additional_gids: Array<number>, 
/**
 * Its effective ids as the host sees them (`/proc/<pid>/status`): the
 * same as `uid`/`gid` without a user namespace, mapped with one.
 */
host_uid: number, host_gid: number, };
