// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who the init process is.
 */
export type Credentials = { 
/**
 * The user and group `config.json` gives it, as the container sees
 * them.
 */
uid: number, gid: number, additional_gids: Array<number>, 
/**
 * Its effective ids as the host sees them (`/proc/<pid>/status`): the
 * same as `uid`/`gid` without a user namespace, mapped with one.
 */
host_uid: number, host_gid: number, };
