// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRuleOrigin } from "./DeviceRuleOrigin";

/**
 * One rule of the device filter.
 */
export type DeviceRule = { allow: boolean, 
/**
 * `c` (character), `b` (block) or `a` (all).
 */
kind: string, 
/**
 * `None`: any.
 */
major: number | null, minor: number | null, 
/**
 * Some of `r` (read), `w` (write), `m` (mknod).
 */
access: string, origin: DeviceRuleOrigin, };
