// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A container on one of its networks, as `inspect` shows it.
 */
export type EndpointSettings = { 
/**
 * The network's name.
 */
network: string, 
/**
 * `--network-alias`, `network connect --alias`: more names for the
 * embedded DNS server.
 */
aliases: Array<string>, 
/**
 * `--ip`, `--ip6`, `network connect --ip/--ip6`: the addresses asked
 * for (otherwise the next free ones).
 */
ipv4_requested: string | null, ipv6_requested: string | null, 
/**
 * The rest only while it runs: the network's id,
 */
network_id: string | null, 
/**
 * its interface inside (`eth0`) and the host's end of its veth pair
 * (`rlv…`),
 */
interface: string | null, host_interface: string | null, 
/**
 * its addresses there,
 */
ip_address: string | null, ip_prefix_len: number | null, gateway: string | null, ipv6_address: string | null, ipv6_prefix_len: number | null, ipv6_gateway: string | null, mac_address: string | null, 
/**
 * the names the embedded DNS server answers for it there,
 */
dns_names: Array<string>, 
/**
 * and whether its IPv4 (IPv6) default route goes through this network.
 */
default_route: boolean, default_route6: boolean, };
