// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * The body of every error response.
 */
export type ErrorBody = { message: string, kind: ErrorKind, };
