// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What went wrong, for programs: the HTTP status says the same in less
 * detail.
 */
export type ErrorKind = "invalid" | "no_such_container" | "no_such_image" | "no_such_exec" | "no_such_network" | "no_such_volume" | "conflict" | "command_not_found" | "command_not_executable" | "internal";
