// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";

/**
 * One event. Container actions: `create`, `start`, `die` (attributes
 * `exit_code`, `oom_killed`; or `error`, when the restart policy couldn't
 * start it again), `oom`, `stop`, `kill` (`signal`), `pause`, `unpause`,
 * `restart` (by the restart policy), `destroy`, `exec_create`,
 * `exec_start`, `exec_die` (`exec_id`, `exit_code`), `health_status`
 * (attribute `health_status`: `healthy` or `unhealthy`, when its
 * healthcheck's verdict changes; a start begins at `starting` without an
 * event), `commit` (attribute `new_image`: the new image's id). Every container
 * event carries `name` and `image`. Image actions, by name, with the
 * image's digest in `id`: `pull`, `tag` (a build, `tag`, `commit` or `load`
 * gave it the name), `untag`, `load` (an unnamed image was loaded; by id),
 * and `delete` once the image itself is gone (named as `rmi` was given it).
 * Network actions: `create`, `destroy`, `connect` and `disconnect`
 * (attribute `container`, running or not); volume actions: `create`,
 * `destroy`.
 */
export type Event = { 
/**
 * RFC 3339 with nanoseconds, UTC.
 */
time: string, kind: EventKind, action: string, 
/**
 * The container's or network's id, or the image's or volume's name.
 */
id: string, attributes: { [key in string]: string }, };
