// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `GET /v1/events`.
 */
export type EventsQuery = { 
/**
 * Replay the recent events at or after this time (RFC 3339, or Unix
 * seconds) before the live ones. The daemon keeps the last 1024.
 */
since: string | null, 
/**
 * Only events of this container (id, prefix or name).
 */
container: string | null, };
