// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";

/**
 * One event. Container actions: `create`, `start`, `die` (attributes
 * `exit_code`, `oom_killed`), `oom`, `stop`, `kill` (`signal`), `pause`,
 * `unpause`, `restart` (by the restart policy), `destroy`, `exec_create`,
 * `exec_start`, `exec_die` (`exec_id`, `exit_code`). Image actions: `pull`,
 * `untag`, `delete`. Every container event carries `name` and `image`.
 * Network actions: `create`, `destroy`, `connect` and `disconnect`
 * (attribute `container`); volume actions: `create`, `destroy`.
 */
export type Event = { 
/**
 * RFC 3339 with nanoseconds, UTC.
 */
time: string, kind: EventKind, action: string, 
/**
 * The container's or network's id, or the image's or volume's name.
 */
id: string, attributes: { [key in string]: string }, };
