// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `201` from `POST /v1/containers/{id}/exec`.
 */
export type ExecCreated = { id: string, };
