// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/containers/{id}/exec`.
 */
export type ExecConfig = { 
/**
 * The program and its arguments (looked up in the container's `PATH`).
 */
cmd: Array<string>, 
/**
 * A PTY of its own.
 */
tty: boolean, 
/**
 * Send the client's input to it.
 */
stdin: boolean, 
/**
 * `KEY=VALUE`, over the container's environment.
 */
env: Array<string>, 
/**
 * `user[:group]`, resolved in the container's `/etc/passwd`; default
 * the container's user.
 */
user: string | null, 
/**
 * Default: the container's working directory.
 */
workdir: string | null, 
/**
 * With `tty`: the terminal's size, `[rows, columns]`, from the start
 * (a resize once it runs would come after its first look).
 */
console_size: [number, number] | null, };
