// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecConfig } from "./ExecConfig";

/**
 * `GET /v1/exec/{id}`.
 */
export type ExecInspect = { id: string, container_id: string, config: ExecConfig, running: boolean, pid: number | null, exit_code: number | null, };
