// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountEntry } from "./MountEntry";

/**
 * The container's filesystem view, from `config.json`.
 */
export type Filesystem = { 
/**
 * The root filesystem on the host (the overlay's merged directory).
 */
rootfs: string, read_only: boolean, 
/**
 * Paths covered (a file by `/dev/null`, a directory by an empty
 * read-only tmpfs), so their contents can't be read.
 */
masked_paths: Array<string>, 
/**
 * Paths remounted read-only.
 */
readonly_paths: Array<string>, 
/**
 * The mounts in the order the runtime makes them.
 */
mounts: Array<MountEntry>, };
