// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a container's healthcheck says.
 */
export type HealthStatus = "starting" | "healthy" | "unhealthy";
