// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A healthcheck: how the daemon tells whether a running container works,
 * by running a command in it now and then (`HEALTHCHECK` in a
 * Containerfile, `--health-*` options, compose's `healthcheck`). Durations
 * are in nanoseconds, as Docker's API and image configs give them; absent
 * or 0 means the default.
 */
export type HealthConfig = { 
/**
 * `["CMD", program, args…]`, `["CMD-SHELL", command]` (run by the
 * image's shell, `/bin/sh -c`), or `["NONE"]`: no healthcheck, not
 * even the image's. Empty: the image's command, with the options given
 * here over its own.
 */
test: Array<string>, 
/**
 * Between checks (default 30 s).
 */
interval: number | null, 
/**
 * A check that takes longer fails, and is killed (default 30 s).
 */
timeout: number | null, 
/**
 * After a start, failures don't count for this long (default 0); a
 * success ends it early.
 */
start_period: number | null, 
/**
 * Between checks during the start period (default 5 s).
 */
start_interval: number | null, 
/**
 * Failures in a row that make the container unhealthy (default 3).
 */
retries: number | null, };
