// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthResult } from "./HealthResult";
import type { HealthStatus } from "./HealthStatus";

/**
 * A container's health: [`ContainerState::health`].
 */
export type Health = { status: HealthStatus, 
/**
 * Checks that failed in a row (those of the start period not counted).
 */
failing_streak: number, 
/**
 * The last checks, at most five, oldest first.
 */
log: Array<HealthResult>, };
