// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One check.
 */
export type HealthResult = { 
/**
 * RFC 3339, UTC.
 */
start: string, end: string, 
/**
 * The command's exit status (0: healthy); -1 when it timed out or
 * couldn't run.
 */
exit_code: number, 
/**
 * What it printed, stdout and stderr together, at most 4 KiB.
 */
output: string, };
