// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line of `uid_map`/`gid_map`: ids `container_id..container_id+size`
 * inside are `host_id..host_id+size` outside.
 */
export type IdMapping = { container_id: number, host_id: number, size: number, };
