// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `POST /v1/images/tag`.
 */
export type ImageTagQuery = { 
/**
 * The image: a name, an id, or a unique prefix of an id.
 */
source: string, 
/**
 * The new name (`app:1.0`), moved from whatever it named before.
 */
target: string, };
