// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/images/save`: the images to put in the archive. The answer
 * is a tar archive (`application/x-tar`): an OCI image layout, with
 * Docker's `manifest.json` beside it, so that `docker load` reads it too.
 */
export type ImageSaveRequest = { 
/**
 * Names or ids; an image named twice is saved once, with both names.
 */
names: Array<string>, };
