// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `DELETE /v1/images`.
 */
export type ImageDeleteQuery = { name: string, 
/**
 * Remove the name even if containers use the image (they keep working:
 * their layers stay until nothing uses them).
 */
force: boolean, };
