// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One layer of an image.
 */
export type ImageLayer = { 
/**
 * The compressed blob's digest (the manifest's).
 */
digest: string, media_type: string, 
/**
 * The compressed blob's size, bytes.
 */
size: number, 
/**
 * The digest of the uncompressed tar stream (the config's
 * `rootfs.diff_ids`).
 */
diff_id: string, 
/**
 * The digest of this layer together with every layer below it: the
 * name of its snapshot.
 */
chain_id: string, 
/**
 * Its snapshot exists.
 */
unpacked: boolean, };
