// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageLayer } from "./ImageLayer";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `GET /v1/images/inspect?name=`.
 */
export type ImageInspect = { 
/**
 * The image config, as stored (the OCI `config` object and the rest).
 */
config: JsonValue, 
/**
 * Per layer, bottom first.
 */
diff_ids: Array<string>, chain_ids: Array<string>, 
/**
 * The layers, bottom first: the manifest's blobs with what they became.
 */
layer_details: Array<ImageLayer>, 
/**
 * Every layer has been unpacked into a snapshot.
 */
unpacked: boolean, 
/**
 * Containers created from it.
 */
containers: Array<string>, 
/**
 * The manifest digest (`sha256:…`): the image's id.
 */
id: string, 
/**
 * Every name pointing at it (`docker.io/library/alpine:latest`).
 */
names: Array<string>, 
/**
 * What the registry called it (an index digest for a multi-platform
 * image), if it was pulled.
 */
repo_digest: string | null, 
/**
 * From the image config, RFC 3339.
 */
created: string | null, 
/**
 * Compressed size of config and layers, bytes.
 */
size: number, layers: number, 
/**
 * `os/arch[/variant]`.
 */
platform: string, };
