// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `GET /v1/images/inspect`.
 */
export type ImageQuery = { name: string, };
