// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer of `DELETE /v1/images`.
 */
export type ImageDeleteResponse = { 
/**
 * Names removed.
 */
untagged: Array<string>, 
/**
 * Blobs and snapshots deleted because nothing uses them any more
 * (digests and chain IDs).
 */
deleted: Array<string>, };
