// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of `rustlet images`: `GET /v1/images`.
 */
export type ImageSummary = { 
/**
 * The manifest digest (`sha256:…`): the image's id.
 */
id: string, 
/**
 * Every name pointing at it (`docker.io/library/alpine:latest`).
 */
names: Array<string>, 
/**
 * What the registry called it (an index digest for a multi-platform
 * image), if it was pulled.
 */
repo_digest: string | null, 
/**
 * From the image config, RFC 3339.
 */
created: string | null, 
/**
 * Compressed size of config and layers, bytes.
 */
size: number, layers: number, 
/**
 * `os/arch[/variant]`.
 */
platform: string, };
