// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Info = { containers: number, running: number, paused: number, stopped: number, images: number, networks: number, volumes: number, 
/**
 * `/var/lib/rustlet`.
 */
data_root: string, 
/**
 * `/run/rustlet`.
 */
run_root: string, 
/**
 * Where container cgroups go (`…/rustletd.service`).
 */
cgroup_parent: string, storage_driver: string, 
/**
 * The OCI runtime binary.
 */
runtime: string, shim: string, kernel: string, cpus: number, 
/**
 * Bytes of RAM.
 */
memory: number, };
