// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { CgroupUsage } from "./CgroupUsage";
import type { Credentials } from "./Credentials";
import type { DeviceRule } from "./DeviceRule";
import type { Filesystem } from "./Filesystem";
import type { IdMapping } from "./IdMapping";
import type { Namespace } from "./Namespace";
import type { Seccomp } from "./Seccomp";

/**
 * The report.
 */
export type Isolation = { id: string, name: string, 
/**
 * Host PID of the container's init.
 */
pid: number, 
/**
 * One per kind, in [`NAMESPACE_KINDS`] order.
 */
namespaces: Array<Namespace>, 
/**
 * Its user namespace's `uid_map`, a mapping per line; empty when it has
 * no user namespace of its own (its ids are the host's).
 */
uid_map: Array<IdMapping>, gid_map: Array<IdMapping>, credentials: Credentials, capabilities: Capabilities, seccomp: Seccomp, filesystem: Filesystem, 
/**
 * The rules of the cgroup's eBPF device filter, in order: the
 * configuration's, the runtime's defaults, `m` for the nodes init
 * creates. Each access (read, write, mknod) of a device is decided by
 * the last rule that matches it and names that access; one no rule
 * names is refused.
 */
devices: Array<DeviceRule>, cgroup: CgroupUsage, 
/**
 * `/proc/<pid>/oom_score_adj`.
 */
oom_score_adj: number, };
