// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `GET /v1/containers`.
 */
export type ListQuery = { 
/**
 * Include containers that aren't running.
 */
all: boolean, };
