// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the NDJSON answer to `POST /v1/images/load` (whose body is
 * the archive: an OCI image layout, as `save` writes, or Docker's older
 * `docker save` format): a `blob` per blob stored, a `loaded` per image,
 * or `error` as the last line.
 */
export type LoadEvent = { "status": "blob", digest: string, size: number, existed: boolean, } | { "status": "loaded", id: string, name: string | null, } | { "status": "error", message: string, };
