// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStream } from "./LogStream";

/**
 * One record: also one line of the NDJSON `logs` response.
 */
export type LogEntry = { 
/**
 * When the shim read it: RFC 3339 with nanoseconds, UTC.
 */
ts: string, stream: LogStream, 
/**
 * The text, including its `\n` (the last entry before an exit may
 * lack one).
 */
log: string, };
