// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `GET /v1/containers/{id}/logs`.
 */
export type LogsQuery = { 
/**
 * Keep the response open and send new entries as they are written,
 * until the container exits (and its last output is sent).
 */
follow: boolean, 
/**
 * Only the last N entries (before following).
 */
tail: number | null, 
/**
 * Only entries at or after this time: RFC 3339, or Unix seconds
 * (fractions allowed).
 */
since: string | null, 
/**
 * Only entries before this time.
 */
until: string | null, stdout: boolean, stderr: boolean, };
