// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memory.events`.
 */
export type MemoryEvents = { low: number, high: number, max: number, oom: number, oom_kill: number, oom_group_kill: number, };
