// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountType } from "./MountType";

/**
 * A container's mount, as `inspect` shows it.
 */
export type MountPoint = { type: MountType, 
/**
 * A volume's name.
 */
name: string | null, 
/**
 * On the host: the volume's directory or the bind source.
 */
source: string, destination: string, read_only: boolean, };
