// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mount of `config.json`.
 */
export type MountEntry = { destination: string, 
/**
 * `proc`, `tmpfs`, `bind`, …
 */
kind: string, source: string, options: Array<string>, };
