// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountType } from "./MountType";

/**
 * One mount of `-v`, `--mount` or `--tmpfs`.
 */
export type MountSpec = { type: MountType, 
/**
 * A volume's name (`None`: a new anonymous volume), or a bind mount's
 * absolute host path. Unused for tmpfs.
 */
source: string | null, 
/**
 * The absolute path in the container.
 */
target: string, read_only: boolean, 
/**
 * Volume: don't copy the image's files into it when it is empty.
 */
no_copy: boolean, 
/**
 * Bind: create the host directory if it is missing (the `-v` syntax
 * does, as Docker's; `--mount` doesn't).
 */
create_host_path: boolean, 
/**
 * Bind, in a container with `--userns=remap`: an idmapped mount, so
 * the host's owners appear as the container's (host root as container
 * root). Volumes always are; host directories only when asked.
 */
idmap: boolean, 
/**
 * Tmpfs: `size=`, in bytes (default: half the RAM, the kernel's).
 */
tmpfs_size: number | null, 
/**
 * Tmpfs: `mode=` (default 1777).
 */
tmpfs_mode: number | null, 
/**
 * Tmpfs: mount flags over the defaults `nosuid,nodev,noexec`
 * (`exec`, `suid`, `dev`, `ro`, …).
 */
tmpfs_options: Array<string>, };
