// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamespaceMode } from "./NamespaceMode";

/**
 * One namespace of the init.
 */
export type Namespace = { 
/**
 * `mnt`, `uts`, `ipc`, `pid`, `net`, `cgroup`, `user` or `time`.
 */
kind: string, 
/**
 * What `config.json` asked the runtime for.
 */
mode: NamespaceMode, 
/**
 * With [`NamespaceMode::Join`]: the namespace file it joined (a pinned
 * network namespace, say).
 */
path: string | null, 
/**
 * The namespace's inode.
 */
inode: number, 
/**
 * The inode of the daemon's namespace of this kind: the host's.
 */
host_inode: number, 
/**
 * `inode == host_inode`.
 */
shared_with_host: boolean, 
/**
 * The other running containers in the same namespace (names).
 */
shared_with: Array<string>, };
