// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a namespace came to be.
 */
export type NamespaceMode = "new" | "join" | "host";
