// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One interface.
 */
export type NetDev = { name: string, rx_bytes: number, rx_packets: number, rx_errors: number, rx_dropped: number, tx_bytes: number, tx_packets: number, tx_errors: number, tx_dropped: number, };
