// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointSettings } from "./EndpointSettings";
import type { NetworkMode } from "./NetworkMode";
import type { PublishedPort } from "./PublishedPort";

/**
 * A container's network, as `inspect` shows it.
 *
 * The top-level addresses are those of its **primary** network: the one
 * its IPv4 default route goes through (else its first), which is also
 * where its published ports lead. `networks` has every network.
 */
export type NetworkSettings = { 
/**
 * `--network`, as given (the first, if it was given more than once).
 */
mode: NetworkMode, 
/**
 * The primary network (or, while it doesn't run, the first it is
 * connected to).
 */
network: string | null, network_id: string | null, 
/**
 * While it runs: `10.89.0.2`.
 */
ip_address: string | null, ip_prefix_len: number | null, gateway: string | null, 
/**
 * While it runs, on an IPv6 network: `fd00:89:0:1::2`.
 */
ipv6_address: string | null, ipv6_prefix_len: number | null, ipv6_gateway: string | null, mac_address: string | null, 
/**
 * Its names on a user-defined network (container name, aliases, short
 * id, hostname).
 */
dns_names: Array<string>, 
/**
 * The pinned network namespace (`/run/rustlet/netns/<id>`), while it
 * runs.
 */
sandbox: string | null, 
/**
 * While it runs: what is published, with the host ports chosen.
 */
ports: Array<PublishedPort>, 
/**
 * Every network it is connected to, in order: what `--network` and
 * `network connect` asked for, and while it runs, its place there.
 */
networks: Array<EndpointSettings>, };
