// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/networks`.
 */
export type NetworkCreate = { name: string, 
/**
 * `10.89.5.0/24`; default: the next free /24 of the daemon's pool.
 */
subnet: string | null, 
/**
 * Default: the subnet's first address.
 */
gateway: string | null, 
/**
 * IPv6 too (dual stack): its bridge and containers get IPv6 addresses
 * as well as IPv4 ones.
 */
ipv6: boolean, 
/**
 * With `ipv6`: `fd00:89:0:5::/64`; default: the next free /64 of the
 * daemon's IPv6 pool (unique local addresses).
 */
subnet6: string | null, 
/**
 * Default: the IPv6 subnet's first address after its own (`…::1`).
 */
gateway6: string | null, 
/**
 * No route out: containers reach each other, not the outside.
 */
internal: boolean, labels: { [key in string]: string }, };
