// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/networks/{id}/connect`: connects a container to the network,
 * at once if it runs, otherwise from its next start.
 */
export type NetworkConnect = { 
/**
 * Its name, id, or a unique prefix of its id.
 */
container: string, 
/**
 * More names for it on this network (a user-defined one).
 */
aliases: Array<string>, 
/**
 * Its address there (a user-defined network); default: the next free.
 */
ipv4_address: string | null, 
/**
 * Its IPv6 address there (an IPv6 network); default: the next free.
 */
ipv6_address: string | null, };
