// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A container's place on a network.
 */
export type NetworkEndpoint = { container_id: string, container_name: string, 
/**
 * `10.89.0.2/24`.
 */
ip_address: string, 
/**
 * `fd00:89:0:1::2/64`, on an IPv6 network.
 */
ipv6_address: string | null, mac_address: string, 
/**
 * The names the embedded DNS server answers for it here.
 */
dns_names: Array<string>, };
