// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkEndpoint } from "./NetworkEndpoint";

/**
 * A network: `GET /v1/networks` lists them, `GET /v1/networks/{id}`
 * shows one (`{id}` is its id, a unique prefix of it, or its name).
 */
export type Network = { id: string, name: string, 
/**
 * Always `bridge` for now.
 */
driver: string, 
/**
 * RFC 3339, UTC.
 */
created: string, 
/**
 * `10.89.0.0/24`.
 */
subnet: string, 
/**
 * `10.89.0.1`: the bridge's address, the containers' default route.
 */
gateway: string, 
/**
 * It has IPv6 as well (`subnet6`, `gateway6`).
 */
ipv6: boolean, 
/**
 * `fd00:89:0:1::/64`.
 */
subnet6: string | null, gateway6: string | null, 
/**
 * The bridge's interface name on the host (`rustlet0`, `rlb…`).
 */
bridge: string, internal: boolean, 
/**
 * The embedded DNS server answers its containers' names (every
 * network but the default one).
 */
dns: boolean, labels: { [key in string]: string }, 
/**
 * The running containers on it.
 */
containers: Array<NetworkEndpoint>, };
