// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `--network`: where a container's network namespace comes from.
 *
 * On the wire it is a string, as in Docker: `bridge`, `none`, `host`,
 * `container:<name or id>`, or the name of a network.
 */
export type NetworkMode = string;
