// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/networks/{id}/disconnect`.
 */
export type NetworkDisconnect = { 
/**
 * Its name, id, or a unique prefix of its id.
 */
container: string, 
/**
 * Also when the network itself is gone: the container's own record of
 * it is removed.
 */
force: boolean, };
