// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

/**
 * `-p`: a container port to publish on the host.
 */
export type PortMapping = { 
/**
 * The host address to listen on; `None` is every address, IPv4
 * (`0.0.0.0`) and IPv6 (`[::]`). `[::]` alone is every IPv6 address.
 */
host_ip: string | null, 
/**
 * `None`: a free port the kernel picks.
 */
host_port: number | null, container_port: number, protocol: Protocol, };
