// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One PSI line: shares of time (percent) stalled, averaged over 10, 60 and
 * 300 seconds, and the total stall time in microseconds.
 */
export type Pressure = { avg10: number, avg60: number, avg300: number, total: number, };
