// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transport protocol of a published port.
 */
export type Protocol = "tcp" | "udp";
