// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer of the prune routes (networks, volumes).
 */
export type PruneResponse = { 
/**
 * Names of what was removed.
 */
deleted: Array<string>, 
/**
 * Bytes freed (volumes).
 */
space_reclaimed: number, };
