// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

/**
 * A published port as a run set it up: the host port is known.
 */
export type PublishedPort = { 
/**
 * `0.0.0.0`: every address, IPv4 and IPv6; `::`: every IPv6 address.
 */
host_ip: string, host_port: number, container_port: number, protocol: Protocol, };
