// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobKind } from "./BlobKind";

/**
 * One line of the NDJSON `pull` response, in order: `resolving`,
 * `resolved`, per blob `exists` or `downloading`… `downloaded`, `done`
 * (the name is stored); then per layer, bottom first, `layer_exists` or
 * `unpacking` + `unpacked`; and last `ready`. A failure at any point ends
 * the stream with `error`. With the `missing` policy and an image already
 * stored, the registry is never contacted: `ready` may follow `resolving`
 * directly. The first part is the same JSON `rustlet_image::pull::Progress`
 * writes.
 */
export type PullEvent = { "status": "resolving", reference: string, } | { "status": "resolved", reference: string, manifest: string, repo_digest: string, platform: string, layers: number, size: number, } | { "status": "exists", kind: BlobKind, digest: string, size: number, } | { "status": "downloading", kind: BlobKind, digest: string, current: number, total: number, } | { "status": "downloaded", kind: BlobKind, digest: string, size: number, } | { "status": "done", reference: string, manifest: string, } | { "status": "layer_exists", chain_id: string, } | { "status": "unpacking", chain_id: string, blob: string, size: number, } | { "status": "unpacked", chain_id: string, entries: number, bytes: number, whiteouts: number, opaque_dirs: number, skipped_devices: number, } | { "status": "ready", reference: string, manifest: string, } | { "status": "error", message: string, };
