// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When to contact the registry.
 */
export type PullPolicy = "missing" | "always" | "never";
