// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullPolicy } from "./PullPolicy";

/**
 * Query of `POST /v1/images/pull`.
 */
export type PullQuery = { reference: string, policy: PullPolicy, };
