// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `DELETE /v1/containers/{id}`.
 */
export type RemoveQuery = { 
/**
 * Kill it first if it is live.
 */
force: boolean, 
/**
 * Remove its anonymous volumes too (`rm -v`).
 */
volumes: boolean, };
