// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestartPolicyName } from "./RestartPolicyName";

/**
 * When a container that has exited is started again.
 */
export type RestartPolicy = { name: RestartPolicyName, 
/**
 * For `on-failure`: give up after this many restarts (0 = never).
 */
max_retries: number, };
