// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeccompRule } from "./SeccompRule";

/**
 * A summary of an OCI seccomp profile.
 */
export type SeccompProfile = { 
/**
 * What happens to a call no rule names (`SCMP_ACT_ERRNO`, …).
 */
default_action: string, 
/**
 * The errno of an `SCMP_ACT_ERRNO` default (`EPERM` is 1).
 */
default_errno: number | null, architectures: Array<string>, 
/**
 * Calls allowed whatever their arguments, sorted.
 */
allowed: Array<string>, 
/**
 * Calls allowed only with certain arguments (`clone` without namespace
 * flags, `personality` with a few values), sorted.
 */
conditional: Array<string>, 
/**
 * Rules with an action other than allow.
 */
other: Array<SeccompRule>, };
