// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rule of a seccomp profile.
 */
export type SeccompRule = { names: Array<string>, action: string, errno: number | null, 
/**
 * Some of its conditions are on the arguments.
 */
conditional: boolean, };
