// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeccompMode } from "./SeccompMode";
import type { SeccompProfile } from "./SeccompProfile";

/**
 * Seccomp, as the kernel enforces it and as it was configured.
 */
export type Seccomp = { 
/**
 * `Seccomp:` in `/proc/<pid>/status`.
 */
mode: SeccompMode, 
/**
 * `Seccomp_filters:`: how many filters are attached.
 */
filters: number, 
/**
 * `NoNewPrivs:`: no `execve` can raise its privileges (setuid bits
 * and file capabilities are ignored). Unprivileged processes need it to
 * install a filter.
 */
no_new_privs: boolean, 
/**
 * The profile in `config.json`; `None` with `seccomp=unconfined` or
 * `--privileged`.
 */
profile: SeccompProfile | null, };
