// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryEvents } from "./MemoryEvents";
import type { NetDev } from "./NetDev";
import type { Pressure } from "./Pressure";

/**
 * One sample. The cgroup fields are what `rustlet-runc events --stats`
 * reports (`rustlet_runtime::cgroups::stats::Stats`), with the same names.
 * Counters are cumulative: a CPU percentage is the difference of
 * `cpu["usage_usec"]` between two samples, over the time between their
 * `read`s, divided by `cpus_online` (or not, for Docker's "100% per CPU").
 */
export type StatsSample = { id: string, name: string, 
/**
 * When the sample was taken: RFC 3339 with nanoseconds, UTC.
 */
read: string, 
/**
 * CPUs online on the host.
 */
cpus_online: number, 
/**
 * `cpu.stat`: `usage_usec`, `user_usec`, `system_usec`, `nr_periods`,
 * `nr_throttled`, `throttled_usec`, …
 */
cpu: { [key in string]: number }, 
/**
 * `memory.current`, bytes.
 */
memory_current: number, 
/**
 * `memory.max`; `None` = unlimited.
 */
memory_max: number | null, memory_peak: number | null, swap_current: number | null, 
/**
 * `memory.stat`: `anon`, `file`, `kernel`, `inactive_file`, …
 */
memory_stat: { [key in string]: number }, memory_events: MemoryEvents, pids_current: number, 
/**
 * `None` = unlimited.
 */
pids_max: number | null, 
/**
 * `io.stat` per device ("major:minor"): `rbytes`, `wbytes`, `rios`, `wios`, …
 */
io: { [key in string]: { [key in string]: number } }, 
/**
 * PSI, per resource (`cpu`, `memory`, `io`) and line (`some`, `full`).
 */
pressure: { [key in string]: { [key in string]: Pressure } }, 
/**
 * The container's interfaces (its network namespace's `/proc/net/dev`).
 */
network: Array<NetDev>, };
