// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `GET /v1/containers/{id}/stats`.
 */
export type StatsQuery = { 
/**
 * A sample every second until the client hangs up (or the container
 * stops); `false`: one sample, as a plain JSON response.
 */
stream: boolean, };
