// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `stop` and `restart`.
 */
export type StopQuery = { 
/**
 * Seconds to wait after the stop signal before killing.
 */
timeout: number | null, };
