// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Version = { 
/**
 * The daemon's version (`CARGO_PKG_VERSION`).
 */
version: string, api_version: string, os: string, arch: string, 
/**
 * `uname -r`.
 */
kernel: string, };
