// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `POST /v1/volumes/prune`.
 */
export type VolumePruneQuery = { 
/**
 * Named volumes too, not only anonymous ones (Docker's `--all`).
 */
all: boolean, };
