// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A volume: `GET /v1/volumes` lists them, `GET /v1/volumes/{name}` shows
 * one.
 */
export type Volume = { name: string, 
/**
 * Always `local`.
 */
driver: string, 
/**
 * Its directory on the host (`/var/lib/rustlet/volumes/<name>/_data`).
 */
mountpoint: string, 
/**
 * RFC 3339, UTC.
 */
created: string, labels: { [key in string]: string }, 
/**
 * Made for a container's `-v /path` or the image's `VOLUME`, with a
 * generated name.
 */
anonymous: boolean, 
/**
 * The containers (by name) that have it among their mounts.
 */
containers: Array<string>, };
