// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query of `DELETE /v1/volumes/{name}`.
 */
export type VolumeRemoveQuery = { 
/**
 * No error if it doesn't exist.
 */
force: boolean, };
