// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/volumes`.
 */
export type VolumeCreate = { 
/**
 * Default: a random 64-hex-digit name (an anonymous volume).
 */
name: string | null, labels: { [key in string]: string }, };
