// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/containers/{id}/wait?condition=`.
 */
export type WaitCondition = "not-running" | "next-exit" | "removed";
