// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer of `wait`.
 */
export type WaitResponse = { 
/**
 * Shell-style exit status.
 */
status_code: number, oom_killed: boolean, error: string | null, };
