[package]
name = "xtask"
description = "Development tasks: `cargo xtask <rootfs|itest|demo|image-run|…>`."
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rustlet-runtime.workspace = true
rustlet-image.workspace = true
rustlet-sys.workspace = true
libc.workspace = true
nix.workspace = true
tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
flate2.workspace = true
hex.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
