//! `cargo xtask gen-ts [--check]`: the daemon API's types in TypeScript, for
//! the desktop app.
//!
//! ```text
//!  crates/rustlet-spec (serde + ts-rs derives)
//!        │  rustlet_spec::export_typescript, 64-bit integers as `number`
//!        ▼
//!  desktop/src/bindings/<Type>.ts   one declaration per file, imports between them
//!  desktop/src/bindings/index.ts    `export type * from "./<Type>"` for each
//! ```
//!
//! The files are committed, so the frontend builds without Rust. `--check`
//! generates them again into a scratch directory and fails if anything
//! differs (CI runs it): a DTO changed in Rust without `gen-ts` breaks the
//! build instead of the app.
//!
//! `u64` becomes `number`, not ts-rs's default `bigint`: `JSON.parse` gives
//! numbers, and every count and size the API sends stays below 2^53.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, bail};

use crate::workspace;

const HEADER: &str = "// Generated by `cargo xtask gen-ts` from crates/rustlet-spec. Do not edit.\n";

pub(crate) fn run(check: bool) -> anyhow::Result<()> {
    let target = workspace().join("desktop/src/bindings");
    let scratch = workspace().join("target/gen-ts");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).with_context(|| format!("remove {}", scratch.display()))?;
    }
    std::fs::create_dir_all(&scratch)?;
    let cfg = ts_rs::Config::new().with_large_int("number").with_out_dir(&scratch);
    rustlet_spec::export_typescript(&cfg).context("export the TypeScript bindings")?;
    write_index(&scratch)?;

    let new = read_tree(&scratch)?;
    let old = if target.exists() { read_tree(&target)? } else { BTreeMap::new() };
    if check {
        let changed: Vec<String> = new
            .keys()
            .chain(old.keys())
            .filter(|p| new.get(*p) != old.get(*p))
            .map(|p| p.display().to_string())
            .collect::<std::collections::BTreeSet<_>>()
            .into_iter()
            .collect();
        if !changed.is_empty() {
            bail!("desktop/src/bindings is out of date ({}); run `cargo xtask gen-ts`", changed.join(", "));
        }
        println!("desktop/src/bindings is up to date ({} files)", new.len());
        return Ok(());
    }
    if target.exists() {
        std::fs::remove_dir_all(&target).with_context(|| format!("remove {}", target.display()))?;
    }
    std::fs::rename(&scratch, &target).with_context(|| format!("move the bindings to {}", target.display()))?;
    println!("wrote {} files to desktop/src/bindings", new.len());
    Ok(())
}

/// `index.ts`: every declaration, so the app imports from one place.
fn write_index(dir: &Path) -> anyhow::Result<()> {
    let mut modules: Vec<String> = read_tree(dir)?
        .into_keys()
        .filter_map(|p| p.to_str().and_then(|s| s.strip_suffix(".ts")).map(str::to_owned))
        .collect();
    modules.sort();
    let mut index = String::from(HEADER);
    for m in modules {
        index.push_str(&format!("export type * from \"./{m}\";\n"));
    }
    std::fs::write(dir.join("index.ts"), index)?;
    Ok(())
}

/// Every file below `dir`, by relative path.
fn read_tree(dir: &Path) -> anyhow::Result<BTreeMap<PathBuf, Vec<u8>>> {
    let mut out = BTreeMap::new();
    let mut stack = vec![dir.to_owned()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d).with_context(|| format!("read {}", d.display()))? {
            let path = entry?.path();
            if path.is_dir() {
                stack.push(path);
            } else {
                let rel = path.strip_prefix(dir).expect("below dir").to_owned();
                out.insert(rel, std::fs::read(&path)?);
            }
        }
    }
    Ok(out)
}
