# Installed as /etc/NetworkManager/conf.d/rustlet.conf
# Tell NetworkManager to leave the Rustlets bridge and veth devices alone;
# otherwise it may try to "manage" them (DHCP, IPv6 autoconf) as they appear.
[keyfile]
unmanaged-devices=interface-name:rustlet*;interface-name:rlv*
