//! Signal dispositions that must be reset before `execve`.
//!
//! On `execve` the kernel resets every *caught* signal to `SIG_DFL` (the
//! handler code is about to disappear), but an *ignored* signal stays ignored,
//! and the blocked-signal mask is inherited unchanged.
//!
//! That matters because Rust's standard library sets `SIGPIPE` to `SIG_IGN`
//! before `main` runs, so that a closed pipe shows up as an `EPIPE` error
//! instead of killing the program. `std::process::Command` quietly undoes this
//! in its children. Our `clone3`-based spawn doesn't go through `Command`, so
//! without [`reset_all_to_default`] every container would start with SIGPIPE
//! ignored: `yes | head -1` would leave `yes` spinning on `EPIPE`, and
//! `/proc/<pid>/status` would show a non-zero `SigIgn` mask.
//!
//! Setting a handler with `sigaction` is `unsafe` in `nix` because the handler
//! runs in signal context, where only async-signal-safe code may run.
//! Installing `SIG_DFL` runs no code of ours at all, which is why a *safe*
//! wrapper is sound here.

use crate::{Errno, Result};

/// Resets the disposition of every signal (1..=`SIGRTMAX`, except the
/// unchangeable `SIGKILL`/`SIGSTOP`) to `SIG_DFL`.
///
/// glibc reserves two real-time signals for its own use and rejects changes
/// to them with `EINVAL`; those are skipped.
pub fn reset_all_to_default() -> Result<()> {
    for sig in 1..=libc::SIGRTMAX() {
        if sig == libc::SIGKILL || sig == libc::SIGSTOP {
            continue;
        }
        set_default(sig)?;
    }
    Ok(())
}

/// Sets one signal's disposition to `SIG_DFL`. `EINVAL` (a signal number the
/// C library keeps for itself) is treated as success.
pub fn set_default(sig: libc::c_int) -> Result<()> {
    // SAFETY: SIG_DFL is not a function pointer; no code of ours will ever
    // run in signal context because of this call.
    let prev = unsafe { libc::signal(sig, libc::SIG_DFL) };
    if prev == libc::SIG_ERR {
        return match Errno::last() {
            Errno::EINVAL => Ok(()),
            e => Err(e),
        };
    }
    Ok(())
}

/// Sets one signal's disposition to `SIG_IGN`, as safe as [`set_default`]
/// for the same reason: no code of ours runs in signal context. A process
/// that must clean up after a child (unmount its rootfs) ignores `SIGINT`
/// meanwhile, so a Ctrl-C meant for the container doesn't kill the cleaner.
pub fn ignore(sig: libc::c_int) -> Result<()> {
    // SAFETY: SIG_IGN is not a function pointer; nothing runs on delivery.
    let prev = unsafe { libc::signal(sig, libc::SIG_IGN) };
    if prev == libc::SIG_ERR { Err(Errno::last()) } else { Ok(()) }
}

/// `si_code` value for signals generated by the kernel itself, e.g. by the
/// terminal driver for Ctrl-C (`SIGINT`), Ctrl-\ (`SIGQUIT`) or a window
/// resize (`SIGWINCH`). `kill(2)` from a process gives `SI_USER` (0) instead.
pub const SI_KERNEL: i32 = libc::SI_KERNEL;

#[cfg(test)]
mod tests {
    use super::*;

    /// Reads the `SigIgn` mask of `/proc/self/status`.
    fn ignored_mask() -> u64 {
        let v = crate::procfs::status_field(None, "SigIgn").unwrap();
        u64::from_str_radix(&v, 16).unwrap()
    }

    #[test]
    fn std_ignores_sigpipe_and_reset_clears_it() {
        // The premise: the Rust runtime ignores SIGPIPE (bit SIGPIPE-1),
        // and test binaries go through the same std startup code as `main`.
        let sigpipe_bit = 1u64 << (libc::SIGPIPE - 1);
        assert_ne!(ignored_mask() & sigpipe_bit, 0, "std should have set SIGPIPE to SIG_IGN");
        // Changing this test process's own disposition is harmless: nextest
        // runs every test in a separate process.
        reset_all_to_default().unwrap();
        assert_eq!(ignored_mask(), 0);
    }
}
